version: 0.2

phases:
  build:
    commands:
      - dotnet test ./src/HelloTests/HelloTests.csproj
      - dotnet publish -c release -o ./build_output ./src/HelloWorldWebCore/HelloWorldWebCore.csproj
artifacts:
  files:
    - build_output/*
    - appspec.yml
    - installApp.sh
